apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 40%
        maxUnavailable: 0%
  selector:
    matchLabels:
      run: hello-world
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
      - name: hello-world
        image: hello-world:kube1
        ports:
        - containerPort: 80